### ISSUE TITLE
Experimental Support for F and S

### ISSUE THREAD

**Issue by Dom1L** [isayev/ASE_ANI#10]
What is the state of the experimental support for fluorine and sulfur atoms?

I got the following error when i tried to calculate the potential energy using ``` mol.get_potential_energy()``` as described in your example files.

```
ERROR: AEVLib Fatal Error detected!

FPN Error -- "Cannot find atomic symbol S in internal index. Check your sae file.
" 
 in location -- /home/jujuman/Gits/NeuroChem/src-aevlib/utilities/datacommander.cpp:57
 in function -- get_idx_for_types()

 Error detected, terminating! 
```

**Comment by Jussmith01** [comment]
S and F networks are currently not available in the repository. Keep an eye out over the next month or two.

**Comment by Dom1L** [comment]
Thank you for your response!

Will this then also include an extension of your dataset towards charged molecules?
